
platform :macos, '10.15'
use_frameworks!

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Runner' do
   ENV['ARCHS'] = 'arm64'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner

  target 'RunnerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
