// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-i96zOJVgr4S4ZMJEHvN0-sNwulXeZEA',
    appId: '1:954233345530:web:b3f2c7bb4ade69f4098043',
    messagingSenderId: '954233345530',
    projectId: 'dotly-49141',
    authDomain: 'dotly-49141.firebaseapp.com',
    storageBucket: 'dotly-49141.firebasestorage.app',
    measurementId: 'G-ERR4QZR27B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTt8KOPAaVYFEQ8mIBVkOcuHAk0uFjNnc',
    appId: '1:954233345530:android:725526019239c53f098043',
    messagingSenderId: '954233345530',
    projectId: 'dotly-49141',
    storageBucket: 'dotly-49141.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvIYqVkxqxKwXApN0xSAjxv-MyIQwKOVk',
    appId: '1:954233345530:ios:af2466c9ceab03de098043',
    messagingSenderId: '954233345530',
    projectId: 'dotly-49141',
    storageBucket: 'dotly-49141.firebasestorage.app',
    iosBundleId: 'com.example.dotly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvIYqVkxqxKwXApN0xSAjxv-MyIQwKOVk',
    appId: '1:954233345530:ios:af2466c9ceab03de098043',
    messagingSenderId: '954233345530',
    projectId: 'dotly-49141',
    storageBucket: 'dotly-49141.firebasestorage.app',
    iosBundleId: 'com.example.dotly',
  );
}